### ISSUE TITLE
Having <!DOCTYPE html> on line 2 throws a warning.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#550] opened 2016-02-03 15:26 UTC
Starting a webpage with <!DOCTYPE html> on the second line makes Oh Noes really angry.

**Comment by kevinbarabash** [comment] 2016-02-03 16:10
confirmed

**Comment by darrylyeo** [comment] 2016-02-04 02:55
This seems similar to issue #281.

**Comment by JavascriptFTW** [comment] 2016-03-07 01:11
I've looked through slowparse, and this bug seems to be caused by the way DOCTYPE's are handled. Slowparse only looks for a DOCTYPE and the very beginning of the document and after that treats everything as if it were a normal HTML tag.

**Comment by kevinbarabash** [comment] 2016-03-07 02:03
A simple fix would be to remove empty lines before sending it slowparse and then correct the position data we get back from slowparse.  It would be best to fix this in slowparse itself though.

**Comment by kevinbarabash** [comment] 2016-04-10 01:43
Closing this as a duplicate of https://github.com/Khan/live-editor/issues/281.

**Closed by kevinbarabash** 2016-04-10 01:43 UTC
Labels: bug, webpage
