### ISSUE TITLE
Allows while loops to crash the browser

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#198] opened 2014-11-10 17:58 UTC
https://www.khanacademy.org/computer-programming/recursive-damage/5984442398277632
The program keeps issuing the println() command over and over until eventually the browser mainly crashes.

**Comment by kevinb7** [comment] 2015-07-06 18:38
closing as a duplicate of https://github.com/Khan/live-editor/issues/331

**Closed by kevinb7** 2015-07-06 18:38 UTC
Labels: bug, pjs
