### ISSUE TITLE
Recent update causes lag in specific programs

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#371] opened 2015-07-27 22:09 UTC
https://www.khanacademy.org/computer-programming/minecraft-ke-more-noise/5971033575129088

After a recent update to the scratchpad code, this program barely runs on my computer, when it used to hit 60.

**Comment by kevinb7** [comment] 2015-07-27 23:10
Thanks for reporting this.  The issue is with the loop protector which prevents infinite loops.  It adds a call to _KAInfiniteLoopProtect inside of every `for` and `while` loops as well inside functions.  I have some ideas of how to make it faster:
- avoid creating function closures
- return immediate n – 1 out of n times

https://github.com/Khan/live-editor/blob/master/js/output/shared/loop-protect.js#L69-L120

**Comment by pamelafox** [comment] 2015-07-28 20:50
I've had a similar report for https://www.khanacademy.org/computer-programming/guess-my-number/6095780544249856/embedded , though I couldn't replicate it myself. Do you suppose it's the same cause?

**Comment by kevinb7** [comment] 2015-07-28 21:36
The embedded one doesn't seem to bad.  I have a fix that uses the "return immediately n – 1 out of n times" approach, but I want to tests it against the minecraft example first.

**Comment by pamelafox** [comment] 2015-07-29 19:12
Here's one more related report:
"https://www.khanacademy.org/computer-programming/connect-4-artificial-intelligence-can-you-beat-it/6428977882464256

Not too long ago, I built a connect 4 AI. It basically brute forced very possible move, which, in turn would take long amounts of time. However, recently, you added a feature which is supposed to prevent infinite loops, but also prevents my AI from working on slow computers, or if I teach it to look more moves ahead. I was wondering if there was any way to change this, as it is quite upsetting. Is there a way I can disable this error (e.g. using try/catch, a variable, or adding a "?KAInfiniteLoopProtect = false" to the end of the web address), or any way that you could detect an actual infinite loop, rather than a seemingly infinite loop?
"

**Comment by kevinb7** [comment] 2015-07-29 21:47
I think we can increase performance, but there will still be some programs like this that we might halt prematurely.  I'm worried about provide a flag like this because it allows users to create links to potentially malicious programs.

**Comment by MikaalSky** [comment] 2015-07-30 02:19
Well, this current setup doesn't really help any students do much with for loops. It slows down programs tremendously.

**Comment by MikaalSky** [comment] 2015-07-31 16:56
From a KA user:
DuckLife is also affected by this issue.

**Comment by kevinb7** [comment] 2015-08-01 17:15
So, my initial fix of bailing out of KAInfiniteLoopProtect early didn't improve the performance much.  I'm going to have to change the approach to insert an "if" statement and only call the the method once in a while.

**Comment by MikaalSky** [comment] 2015-08-16 06:44
Is this still actively being worked on?

**Comment by kevinb7** [comment] 2015-08-16 14:50
It is.  I've submitted a diff using our internal code review tool.  Unfortunately the fix is not a simple one so it may take some time to get through review.  My hope is to get it deployed by Friday.

**Comment by kevinb7** [comment] 2015-08-19 20:48
Fixed by https://github.com/Khan/live-editor/commit/55a8053293db945395e687ddab98b8bb71007fa5 and deployed.  @MikaalSky you can re-enable the minecraft example... with noise.  ^_^

**Closed by kevinb7** 2015-08-19 20:48 UTC
Labels: performance, pjs
