### ISSUE TITLE
KA Javascript is now a distinct (and wrong) dialect

### ISSUE THREAD

**Issue by lgto4** [Khan/live-editor#445] opened 2015-10-15 03:18 UTC
Refer to the simple demo program at https://www.khanacademy.org/computer-programming/wat/5726354510315520 .

The program declares var mouseClciked = inside of the draw function.  Being a local variable, the assignment should have no affect on Processing.js.  Alas, through a rewrite bug the local variable assignment is magically hoisted to a global variable assignment.

This is very bad.  Beginners need to learn when and how to use "var".  And, the language at KA is no longer Javascript.

**Comment by kevinbarabash** [comment] 2015-10-15 03:46
@lgto4 agreed.  This is a fixable problem, but there are many existing programs have have code that does this.  I think that we should first provide warnings against this.  After the warnings have been live on the site for a while then we can change the behavior.  It might also help to have some sort of common mistakes video on the site too.  @pamelafox thoughts?

**Comment by lgto4** [comment] 2015-10-15 03:56
@kevinbarabash: I should hope that the bug is fixable.  There can't be that many programs that have been led astray since the bug was injected with the most recent rendition of the KA infinite loop detector. Furthermore, breakage has never stopped the "forward" progress of KA features. It certainly should not stop the correction of an insidious bug.

**Comment by kevinbarabash** [comment] 2015-10-15 04:04
@lgto4 I thought this was always the behavior.  How do you know that this bug started with the loop detector?

**Comment by kevinbarabash** [comment] 2015-10-15 04:08
@lgto4 after some investigation, I think you're right about when it was introduced.  This bug should be pretty easy to fix.  I'll try to get to it sometime this week.

**Comment by lgto4** [comment] 2015-10-15 04:11
@kevinbarabash: Thanks for your attention to this issie.  I apologize for sitting on it. I am pretty clueless when it comes to dealing with github...

**Comment by kevinbarabash** [comment] 2015-10-15 16:05
@lgto4 no worries.  If you have an github related questions, ask away.  There's also a gitter chat room for this project: https://gitter.im/Khan/live-editor.

**Comment by Potato42** [comment] 2015-10-15 17:56
This is an extremely easy to fix bug.  Basically only one line needs to be removed: https://github.com/Khan/live-editor/blob/master/js/output/pjs/pjs-ast-transforms.js#L127.  I believe this should do it https://github.com/Khan/live-editor/pull/447.

However, this will break at least a few programs.

**Comment by Potato42** [comment] 2015-10-15 18:57
Wait, never mind, that doesn't seem to work.  -_-

**Comment by JavascriptFTW** [comment] 2015-10-17 15:12
I've been looking into fixing this the past few days, and it's actually more difficult than it seems at first glance. I've "fixed" the basic problem reported in this issue, but while testing I've discovered that there really isn't an "easy" fix that covers all cases.
I've made some examples of the edge cases of this issue that I've discovered [here](https://www.khanacademy.org/computer-programming/super-edge-cases/4882814894473216).

These edge-cases _could_ be fixed by checking if a variable already has been declared in the current scope or one above it with the same name as whatever draw method we think the user is assigning to whenever we encounter an `AssignmentExpression`. I'm not entirely sure whether you want to be doing that though as these are _very_ edge cases.

**Comment by Potato42** [comment] 2015-10-17 17:14
@JavascriptFTW Wait, are you trying to stop the edge-cases from working or make them work?  I can't see why they shouldn't work as something like

    var x = 2;
    var y = function() {
        var z = function() {
            x = 3;
        };
        
        z();
    };
    y();
    
    println(x);

works, but if they don't work, we should just tell rewriteContextVariables about those functions being in the global scope when we call it.
If they do work, we should leave them alone as it is expected behavior.

**Comment by lgto4** [comment] 2015-10-17 17:32
@JavascriptFTW I looked at your three test cases.  I'm not sure if the invocation of println in the latter two indicates disappointment.  In the later two cases, a function is simply assigned to a global variable, so we are happy to see println invoked.

In the first case, the keyword `var` indicates that the variable is local to the function.

**Comment by lgto4** [comment] 2015-10-17 17:44
@JavascriptFTW Why is it in my case (your case #1), if I change the local variable name from "mouseClicked" to "red", the program is apparently flawless?  Similarly, if I remove the var prefix, I get the expected complaint from Yoko Oh Noes.

I am mystified about the attributes of "red" versus those of "mouseClicked" wrt the KA Javascript compiler's rewriting rules...

**Comment by JavascriptFTW** [comment] 2015-10-17 18:01
@lgto4 The invocation of `println` in the latter two test cases is unexpected behaviour. What they _should_ do is set the _local_ variable `mouseClicked` (according to how scope works), but what they actually do is set the global variable which is not at all how JavaScript (or most languages for that matter) works.

I'm not entirely sure what you mean about "red" vs. "mouseClicked".

**Comment by JavascriptFTW** [comment] 2015-10-17 18:02
@Potato42 I'm trying to make the edge cases work _properly_.

**Comment by Potato42** [comment] 2015-10-17 18:40
@JavascriptFTW If you leave out `var` in JavaScript, you modify the global scope.  That's how JavaScript works.  Go ahead and test it if you don't believe me.

**Comment by lgto4** [comment] 2015-10-17 18:40
@JavascriptFTW  My bad!  I assumed that program was used to generate three different test programs, each program with only one of the three cases...

In _my_ test program if if I change the local variable name from "mouseClicked" to "red", the program is apparently flawless.

Both "red" and "mouseClicked"  are Processing.js defined global variables.  Why doesn't this bug affect "red"?

**Comment by JavascriptFTW** [comment] 2015-10-17 19:10
@Potato42 I'd recommend that you run this

    var a = 2;
    var b = function() {
        var a = 3;
        a = 4;
    };
    println(a);

and tell me if it prints out 4, since that is effectively what you are saying will happen.

**Comment by kevinbarabash** [comment] 2015-11-11 00:11
Fixed by https://github.com/Khan/live-editor/pull/489.

**Closed by kevinbarabash** 2015-11-11 00:11 UTC
Labels: pjs

**Comment by lgto4** [comment] 2015-11-11 01:48
So, when does the common man see the fix?

**Comment by kevinbarabash** [comment] 2015-11-11 02:07
@lgto4 I'll try to do a deploy sometime this week unless @pamelafox does one first.
