### ISSUE TITLE
println does not deal with literal arrays

### ISSUE THREAD

**Issue by lgto4** [Khan/live-editor#623] opened 2016-11-29 00:54 UTC
`println([ 1, 2 ]);` causes gripes from Yoko Oh Noes.

**Comment by MatthiasSaihttam** [comment] 2016-11-29 01:16
Duplicate of #542. Which was also opened by you.

**Comment by lgto4** [comment] 2016-11-29 03:55
You'd think I would wait at least a year before forgetting it.  Well, I guess that evens out the reports marked as fixed that are not.

**Closed** 2016-11-29 13:33 UTC
