### ISSUE TITLE
debug() is displaying the Program object, not what's passed to it

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#464] opened 2015-10-28 18:24 UTC
Reported by Darryl on ZenDesk

1. Open https://www.khanacademy.org/computer-programming/debugarg1-arg2-processingjs/939146973
2. Open console. 
3. See "Object"
4. Expand object and see it contains Program object.

Expected: the arguments passed to debug().

**Comment by Potato42** [comment] 2015-10-28 19:16
Interesting.  Based on `println(debug);`, it almost looks like the `arguments` in the debug function is being automatically replaced by a variable that contains the arguments of another function or something.

**Comment by kevinbarabash** [comment] 2015-10-29 03:25
This is caused by the fact that fat arrow functions can't access `arguments`.  I'm rewriting this to use rest parameters to pass all arguments to `console.log`.

**Comment by kevinbarabash** [comment] 2015-11-09 01:49
Fixed by https://github.com/Khan/live-editor/commit/17adf5ab2119dc1ba76d1b117ca15cbd7e031919.

**Closed by kevinbarabash** 2015-11-09 01:49 UTC
Labels: bug, pjs, regressionbug
