### ISSUE TITLE
Can't make a object instance when the object constructor is passed into a function

### ISSUE THREAD

**Issue by petercollingridge** [Khan/live-editor#496] opened 2015-11-16 20:54 UTC
The following code gives an error: Cannot read property 'prototype' of undefined.

    var makeObj = function(obj) {
      return new obj();
    };

    var x = makeObj(Array);

It worked about 10 days ago. It's not a big deal, but I've seen a few programs broken as a result of it.

**Comment by kevinbarabash** [comment] 2015-11-16 21:50
This probably has to do with a recent change to rewrite `NewExpressions` using an AST transform as opposed to a regex.  @Gigabyte-Giant if you have some time could you look at this?

**Comment by Gigabyte-Giant** [comment] 2015-11-16 21:51
I was just looking over this @kevinbarabash. Give me a bit and I'll get back to you.

**Comment by MikaalSky** [comment] 2015-11-16 22:00
I'm not sure it's neccasary to make arrays like that but I can see for instance where you could put a Object in a parameter to create a new instance and append it but hardcoding it would make sense to do 99% of the time. Might as well get it fixed though.

**Comment by Gigabyte-Giant** [comment] 2015-11-16 22:08
Okay, I've determined what I *think* the problem is; [my AST transform](https://github.com/Khan/live-editor/blob/master/js/output/pjs/pjs-ast-transforms.js#L293-L319) **always** prefixes identifiers with `__env__`, which is fine, unless you're referencing a function parameter (or at least that's what I can tell from my quick test).

I broke it, so I'll fix it. I'll also write a a new test to make sure that won't happen again.

Sorry about that, guys!

**Comment by kevinbarabash** [comment] 2015-11-17 01:19
@Gigabyte-Giant this is a regression.  Thanks for fixing.

**Comment by petercollingridge** [comment] 2015-11-17 11:54
Wow, that was very quick, thank you!

@MikaalSky I just used `Array` as a simple example; none of the programs I saw were actually doing this, they were all using custom objects.

**Comment by petercollingridge** [comment] 2015-11-17 12:11
I think there's still a related issue, since it gives the same error and broke at around the same time.

The problem is from this program (which has been fixed by commenting out some parts): https://www.khanacademy.org/computer-programming/_/6380002294366208

The issue seems to be due to defining and creating an object inside a self-invoking function, like this:

    (function() {
        var f = function() {};
        var g = new f();
    })();

Again, it doesn't seem a massive problem, since hardly anyone is going to do this, but just to let you know.

**Comment by Gigabyte-Giant** [comment] 2015-11-17 13:41
Hi @petercollingridge! Thanks for providing me with another test case. I ran the code you provided, against my branch, and all appears to work just fine (in other words, my PR should resolve all of those issues).

**Comment by kevinbarabash** [comment] 2015-11-17 15:57
Resolved by https://github.com/Khan/live-editor/pull/497.

**Closed by kevinbarabash** 2015-11-17 15:57 UTC

**Comment by pamelafox** [comment] 2015-11-20 06:03
This fix is deployed, can you verify the fix?
