### ISSUE TITLE
CSS does not respect embed dimensions

### ISSUE THREAD

**Issue by JetStarBlues** [Khan/live-editor#646] opened 2017-10-21 19:24 UTC
The minimum width imposed by the CSS is larger than the actual minimum width of a program (400px). I'm assuming this is to ensure space for the editor, but when a program is embedded sometimes the user wants only the program and not the editor (and configures their embed as such using the embed options provided).

	<style type="text/css" data-aphrodite>
	.wrapScratchpad_vw13lu{
		min-width:800px !important
	}
	</style>

**Comment by pamelafox** [comment] 2018-06-26 21:44
This looks to be an issue with our internal code that lives outside of live-editor. Can you report it via ZenDesk, provide a link to an example that shows this issue, and send me a link to the ZenDesk?

(I'm going to close it here, to keep these issues as only ones that can be solved in this repo. Let me know if I've made a mistake in thinking the issue is outside this repo).

**Closed by pamelafox** 2018-06-26 21:44 UTC

**Comment by JetStarBlues** [comment] 2018-06-28 17:33
Hi
It seems to have been fixed sometime between when I first posted and now. The same pages now render correctly.

**Comment by pamelafox** [comment] 2018-06-28 19:01
That's great to hear! The best bugs are the ones that no longer exist. :)
