### ISSUE TITLE
Strange behavior with fill() autocomplete in talk-through recording

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#349] opened 2015-07-07 00:11 UTC
I just recorded this talk-through:
https://www.khanacademy.org/computer-programming/special-processingjs-functions/5076945701306368

If you watch at around -2:04, you'll see me write fill(mouseX, mouseY, mouseY);
It's all well and good, but then if you pause at any point, you'll see the fill() autocomplete come in, with 255, 0, 0); and it places it at a bad spot, causing the code to be error-full.

**Comment by kevinb7** [comment] 2015-07-07 16:20
I don't have computer-programming/special-processingjs-functions/5076945701306368 locally, if I update my datastore will that grab it?

**Comment by pamelafox** [comment] 2015-07-07 16:35
Probably not, since I made it yesterday. But, I was able to replicate it locally with a quick talk-through:
1. Go to /cs/new/pjs
2. Click record
3. Type
draw = function() {
fill(mouseX, mouseY, mouseZ);
ellipse(10, 10, 10, 10);
}
4. Save recording
5. Play it, and jump forward, see same issue
<img width="365" alt="screen shot 2015-07-07 at 9 35 29 am" src="https://cloud.githubusercontent.com/assets/297042/8551456/86d36996-248b-11e5-9596-16850addc9d4.png">

**Comment by kevinb7** [comment] 2015-07-07 17:03
I was able to reproduce the bug.  I'm going to work on this right now because I think it probably impacts the most people.  Let me know if you'd rather me work on something else.

**Comment by kevinb7** [comment] 2015-07-07 23:57
Fixed in https://github.com/Khan/live-editor/commit/85def8f51b0f91665041382fc305dc4ffd33109b.

**Closed by kevinb7** 2015-07-07 23:57 UTC
Labels: bug, pjs
