### ISSUE TITLE
All audio on browser breaks after using playSound() really fast.

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#224] opened 2015-01-09 23:41 UTC
Find a program with sound that you can click to play.
Make sure it plays 2 sounds at a time.
Keep clicking rapidly. Eventually the browser should stop playing audio until a restart.

**Comment by pamelafox** [comment] 2015-01-09 23:43
Can you give an example program, and like the other one, tell me any JS errors that you see?
This one might be a browser issue.

**Comment by MikaalSky** [comment] 2015-01-09 23:48
Actually, here's a better way to reproduce:
(use firefox)
Go here:https://www.khanacademy.org/computer-programming/ka-music-maker-experimental/6254496473415680
Open another tab at this link but go back to previous tab: https://www.khanacademy.org/computer-programming/just-the-text/6382441594617856
Click the canvas of the first tab
Go to the second tab and click
Sounds will suddenly fail to work on any webpage.

**Comment by kevinb7** [comment] 2015-02-15 17:42
I have a feeling that pull request https://github.com/Khan/live-editor/pull/243 will fix this as well.

**Comment by kevinb7** [comment] 2015-07-10 04:33
@MikaalSky could you try reproducing this?

**Comment by MikaalSky** [comment] 2015-07-10 04:56
Will do. Its late here, though, so I'll test this tommorow

**Comment by kevinb7** [comment] 2015-07-12 03:00
I had a look at the music maker program.  It's loading sounds from variables which is failing because sounds are loading asynchronously now.  This is now a duplicate of https://github.com/Khan/live-editor/issues/302 which I'll try to tackle next week.

**Closed by kevinb7** 2015-07-12 03:00 UTC
Labels: bug, pjs
