### ISSUE TITLE
get() doesn't work with translate() and for some browsers, background()

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#381] opened 2015-08-17 20:50 UTC
Reported on ZenDesk by Peter.

"There are two problems with get(): * 
* the coordinates specified in the arguments are not translated by translate() 
* the returned value is incorrect after a background() change (Chrome)"

We don't teach get() anywhere in the curriculum, and I specifically avoided it as I knew it had performance issues, so this is not high priority, but any interested parties are welcome to take this on.

The first step is to look to see if the core ProcessingJS repo has already addressed this issue, or if it's an issue with both the variants.

**Comment by GoToLoop** [comment] 2015-08-17 22:13
AFAIK, **get()** belongs to a set of functions which aren't affected by any transformations.
The coordinates origin is fixed at (0, 0) always.

**Comment by MikaalSky** [comment] 2015-08-18 11:46
I could not reproduce any actual issues using get().

**Comment by Gigabyte-Giant** [comment] 2015-08-22 22:13
I think I reproduced the issue... See [this program](https://www.khanacademy.org/computer-programming/reproduced-381/4606202634960896).

You'll notice, if you comment out `translate` and change the parameters in `get` from `0` to `200`, everything works the way it should...

**Comment by kevinb7** [comment] 2015-08-22 22:19
I change the `get` params to `200, 200` and the background turned blue.  I commented/uncommented the `translate` and the result was the same.  I tested on Chrome, Firefox, and Safari on Mac OS X 10.10.   @Gigabyte-Giant which browser/os combo are you seeing the issue on?

**Comment by Gigabyte-Giant** [comment] 2015-08-24 19:55
@kevinb7 I edited my above post. There is no issue.

**Comment by kevinb7** [comment] 2015-08-25 03:59
Maybe the user's expectation of what `get` should differs from what `get` is supposed to do.

**Comment by MikaalSky** [comment] 2015-08-25 12:07
There is no get course so I could see why.

**Comment by GoToLoop** [comment] 2015-08-25 12:27
Reading **get()**'s reference from Processing's site: https://processing.org/reference/get_.html
It states it's neither affected by **imageMode()** nor **colorMode()**.
And that it's merely a slower & more convenient _pixels[]_ alternative.
So it's assumed it's not affected by any transformations either. Just like _mouseX_ & _mouseY_.

**Comment by kevinb7** [comment] 2015-08-26 01:50
Closing it.  Thanks @GoToLoop for providing references to the docs.

**Closed by kevinb7** 2015-08-26 01:50 UTC
Labels: bug, pjs
