### ISSUE TITLE
Strange output from println() when passing "new Obj()"

### ISSUE THREAD

**Issue by pamelafox** [Khan/live-editor#324] opened 2015-06-16 23:22 UTC
Reported on ZenDesk. Low priority as I suspect it's pretty rare that folks run into this, but someone can pick this up if they'd like.

"An odd glitch that I found accidently. It's pretty easy to get around, as shown in my program.

Basically the issue is that when printing text to create a new object (e.g "println(new Obj());" it will give a long and odd output.

(See the link of the issue to see exactly what I mean)."
"https://www.khanacademy.org/computer-programming/possible-ka-glitch/5953780493451264"

**Comment by Gigabyte-Giant** [comment] 2015-06-16 23:37
You'll notice that if you use `print`, instead of `println`, that doesn't happen. This is (from what I can tell), due to the way that PJS does `e.print.apply` for `println`.

Ref: https://github.com/processing-js/processing-js/blob/f72e3c3442a90a1a36614e88e83fdc97a04a76a3/src/Helpers/PjsConsole.js#L110

**Comment by kevinb7** [comment] 2015-06-17 00:54
It's caused by this (pjs-output.js::injectCode):
```
    userCode = userCode && userCode.replace(
        /\bnew[\s\n]+([A-Z]{1,2}[a-z0-9_]+)([\s\n]*\()/g,
       "PJSOutput.applyInstance($1,'$1')$2");
```
The issue is that it's doing a blind replace on the source code and replacing the "new Obj()" that's inside the string as well when it shouldn't.  Probably not a huge deal for users.  Could be fixed with a more complex regex (maybe).

**Comment by Gigabyte-Giant** [comment] 2015-10-12 16:48
I just submitted a PR that resolves this issue via AST Transforms.

**Closed** 2015-11-09 20:21 UTC
Labels: bug, pjs
