### ISSUE TITLE
.toString() on functions should return the original user code

### ISSUE THREAD

**Issue by lgto4** [Khan/live-editor#449] opened 2015-10-16 04:21 UTC
The Khan Academy Javascript compiler now strips comments from functions and objects when it recasts them into its  __env__ venacular.  I and hand of others would appreciate it if the compiling left the comments intact.

**Comment by Gigabyte-Giant** [comment] 2015-10-16 14:39
Out of curiosity, might I ask *why*?

The comments aren't removed from the code that we see (as you know), they just aren't in the code that goes through the code injection and AST transforms.

**Comment by MikaalSky** [comment] 2015-10-16 14:52
@Gigabyte-Giant People really like to read from the comments in functions for things like writing custom "code" and parsing it with a custom parser. Some people even write custom markup parsers and send it through like that.

**Comment by Gigabyte-Giant** [comment] 2015-10-16 14:54
Fair argument, however, before this can really move forward, something needs to happen with [this](https://github.com/Khan/live-editor/issues/400), agreed?

**Comment by MikaalSky** [comment] 2015-10-16 14:56
@Gigabyte-Giant Solving that issue would also solve this issue, so yes.

**Comment by kevinbarabash** [comment] 2015-10-16 15:53
In solving https://github.com/Khan/live-editor/issues/400 we could tell esprima to attach range information to the AST and then use that to grab a substring of the original user code based on the range of each FunctionExpression node.

**Comment by lgto4** [comment] 2015-10-16 22:27
@Gigabyte-Giant: I have programs that emit code. It would be much better of the comments came along with the code.  My code is obtuse enough *with* the comments.  Examples include https://www.khanacademy.org/computer-programming/button-generator/1847123742  https://www.khanacademy.org/computer-programming/handbook-of-collisions-and-interiors/5567955982876672  and  https://www.khanacademy.org/computer-programming/images-52/1405420533

**Comment by Gigabyte-Giant** [comment] 2015-10-16 22:29
@lgto4 got it, thanks.

**Comment by lgto4** [comment] 2015-10-16 22:30
It's pretty easy to write your own filter to remove the __env__ glop.  Besides, if you can't see it, then how can you work around it?

**Comment by kevinbarabash** [comment] 2015-11-09 02:00
I'm going to resolve this as a duplicate of https://github.com/Khan/live-editor/issues/400.  Once that is resolved, the comments will appear in the results of `.toString()` like before.

**Comment by kevinbarabash** [comment] 2016-03-13 21:47
Resolving as duplicate now.

**Closed by kevinbarabash** 2016-03-13 21:47 UTC
Labels: pjs
