### ISSUE TITLE
Allow HTML JS to run even if it takes a while

### ISSUE THREAD

**Issue by Cis112233** [Khan/live-editor#583] opened 2016-05-09 21:49 UTC
I am working on [porting a game to KA](https://www.khanacademy.org/computer-programming/new-webpage/5352485836) while making sure to use the proper license rules and ran into a problem. I have bug free JS that checks out but it is a few thousand lines long. I get the EB error that my JS is taking too long. Could we add a way to "continue" loading the JS even if it takes a while? I think this would allow more creative/long programs to run on KA.

**Comment by MikaalSky** [comment] 2016-05-10 18:37
I believe there's already an issue for this.

**Comment by kevinbarabash** [comment] 2016-05-11 06:19
@Cis112233 what kind of things are you trying to do that take a long time?

**Comment by Cis112233** [comment] 2016-05-11 12:15
The link I gave has a few thousand lines of code. I am trying to port candy box 2
@Cis112233 what kind of things are you trying to do that take a long time?

---

**Comment by brew4321** [comment] 2016-05-17 00:35
There have been several issues about loops taking to long. I created #446 which seems to be the same as this one. Is there a way to like merge similar issues here?

**Comment by kevinbarabash** [comment] 2016-05-18 01:24
Closing as a duplicate of https://github.com/Khan/live-editor/issues/446.

**Closed by kevinbarabash** 2016-05-18 01:24 UTC
