### ISSUE TITLE
Some "unsafe" calls are being marked as "safe" calls in production

### ISSUE THREAD

**Issue by MikaalSky** [Khan/live-editor#253] opened 2015-02-16 20:03 UTC
When pasting this program's code into the demo
https://www.khanacademy.org/computer-programming/minecraft-ke-trees/5971033575129088
you get a random nbox error that doesn't happen with the KA editor.

**Comment by kevinb7** [comment] 2015-02-16 23:43
This one is a little worrisome.  There are some notes in pjs-output.js that ```createGraphics``` doesn't work in workers, but the "undefined is not a function" error is occurring in the main thread during the "grabAll" phase of ```injectCode```.  Specifically, it replaces function unsafe calls with stubs that look like this:
```
function () {
    if (typeof fnCalls !== "undefined") {
        fnCalls.push([global, arguments]);
    }
    return 0;
}
```
The problem is that @MikaalSky's example tries to access properties on the result of ```createGraphics``` which is ```0```.
```
var nBox = createGraphics(40,40,P2D);
nBox.background(255,255,255,0);  // 0.background(...) => Oh noes!
```
I'm going to investigate what's happening in production with ```injectCode```.

@pamelafox it might be prudent to delay any pushes to production until this one is resolved.

**Comment by kevinb7** [comment] 2015-02-17 00:13
This is actually quite interesting.  In ```PJSOutput.initialize``` we check all of the methods in Processing to determine which are safe using this code:
```
if (this.idempotentCalls.indexOf(processingProp) !== -1 ||
    /native code/.test(strValue) ||
    /return /.test(strValue) &&
    !/p\./.test(strValue) &&
    !/new P/.test(strValue)) {
         safeCalls[processingProp] = true;
    }
```
This code is exactly the same in dev and production.  The thing that's changing is the implementation of the processing methods when the code is minified.  This is what ```createGraphics``` looks like in development:
```
function (w, h, render) {
      var pg = new Processing();
      pg.size(w, h, render);
      return pg;
}
```
So it fails the ```!/new P/.test(strValue)``` part of the test.

In production though, ```createGraphics``` looks like this:
```
function (e,t,n) {
   var r=new L
   r.size(e,t,n)
   return r
}
```
No ```new Processing();``` so it passes.  There may be other methods in production that are being marked as "safe" when they're not supposed to be.  In this case I think it's okay to add ```createGraphics``` to the list of ```idempotentCalls``` because it doesn't actually change any of the state in ```this.canvas```.

More generally speaking ```!/p\./.test(strValue) && !/new P/.test(strValue))``` has no effect in production and should probably be removed from production code.  As a replacement, it might be better to have a script compute the whitelist/blacklist (whichever is shorter) as part of the build process and include the result as a variable in PJSOutput.

@jeresig @pamelafox thoughts?

**Comment by kevinb7** [comment] 2015-02-17 00:21
Another thought... it would be nice to run the tests against minified code.  It might turn up other subtle bugs like this.

**Comment by kevinb7** [comment] 2015-07-17 05:35
This was fixed a while ago in https://github.com/Khan/live-editor/commit/b7b371de00dc0c677c056fd7358cbe8639f2e710.

**Closed by kevinb7** 2015-07-17 05:35 UTC
Labels: bug, demo, pjs
