### ISSUE TITLE
Error crashing LE

### ISSUE THREAD

**Issue by Cis112233** [Khan/live-editor#592] opened 2016-06-20 18:34 UTC
https://www.khanacademy.org/computer-programming/escape/6556810072817664 When working on that program I noticed that if you jump around and get hit by bullets the LE crashes about 1/10 times. When using "Try" and "Catch" I get the error:
"TypeError: _env_.bullets[i] is undefined"
When you un comment the try/catch when you get the error in the dev console EB does not tell you the error. The LE crashes and nothing works.

**Comment by MatthiasSaihttam** [comment] 2016-06-20 20:38
I went ahead and [simplified the code](khanacademy.org/cs/i/6715456460554240) as much as I could, just to make evident the problem. Namely, you splice an object from its array, then try to call a method of that object.

**Comment by Cis112233** [comment] 2016-06-20 21:59
Yeah sorry about not making a simple example





 
        Christopher
                   
                          


Date: Mon, 20 Jun 2016 13:38:55 -0700

**Comment by kevinbarabash** [comment] 2016-07-06 05:09
@MatthiasSaihttam the link you posted isn't working for me.  It sounds like it's a bug in the user code not in live-editor, although the error message could be improved.

**Comment by MatthiasSaihttam** [comment] 2016-07-06 05:14
Sorry about the link. I hadn't included "https://", so it was pointing to a Github address. It's definitely a bug with the user code, the problem is that the instead of having Oh Noes show up with the error, the live editor crashes/freezes and the error gets written to the console.

**Comment by kevinbarabash** [comment] 2016-07-12 00:41
I tried reproducing the issue in the link by commenting out the `// if (i === 2) {` and restarting the program.  Error buddy showed an error message that says "Cannot read property 'doMyThing' of undefined".

**Comment by MatthiasSaihttam** [comment] 2016-07-12 16:10
Weird. I don't get an error, no matter what I do or what browser I use.

**Comment by kevinbarabash** [comment] 2016-07-14 15:09
In that case I'm going to close this.

**Closed by kevinbarabash** 2016-07-14 15:09 UTC
